### ISSUE TITLE
Issue with import from serial

### ISSUE THREAD

**Issue by amcar-dtu** [cobolt-lasers/pycobolt#4]
Ref. line: https://github.com/cobolt-lasers/pycobolt/blob/001e929e979c270ee9598ef39233d3ebb4b73470/pycobolt/pycobolt/pycobolt.py#L3

Got puzzled by this error for some minutes:

```
File "d:\mypackage\cobolt.py", line 2, in <module>
    import pycobolt
  File "D:\mypackage\.venv\Lib\site-packages\pycobolt\__init__.py", line 1, in <module>
    from  pycobolt.pycobolt import *
  File "D:\mypackage\.venv\Lib\site-packages\pycobolt\pycobolt.py", line 3, in <module>
    from serial import SerialException
ImportError: cannot import name 'SerialException' from 'serial' (unknown location)
```

and just realised that the line should be corrected as:
```python
from serial.serialutil import SerialException
```

**Comment by Charlotte-Cobolt** [comment]
Thank you for reporting the issue, we will adress it.

Which version of python and pyserial are you using?

**Comment by amcar-dtu** [comment]
Hi @Charlotte-Cobolt ,

here you go:

```bash
─❯ python --version
Python 3.10.11

─❯ poetry show pyserial 
 name         : pyserial
 version      : 3.5
 description  : Python Serial Port Extension 

required by
 - pycobolt >=3.5
 ```

**Comment by Charlotte-Cobolt** [comment]
Hi @amcar-dtu 

We were only successful reproducing this bug when we installed the package "serial" and then uninstalled it again, as the package "serial" creates a conflict with pyserial. 

Therefore, it should be considered a bug of pyserial rather than of pycobolt. However, we might still adress it when pushing some upgrades of pycobolt that are in the pipeline.

Thank you for reporting the issue and feel very free to contact us for any further inquiries
